### ISSUE TITLE
Can login steps be 1 step in the step definition?

### ISSUE THREAD

**Issue by lewisp-nhs** [tolajobi/SauceDemo_Cypress_Framework#3]
https://github.com/tolajobi/SauceDemo_Cypress_Framework/blob/bb47a6cfceae2af5dc7b92b4e795175c28e491e6/cypress/e2e/OrderItem.feature#L34C1-L36C35

**Comment by tolajobi** [comment]
I separated the login steps in case I need it for negative login scenarios
